#!/bin/bash

#migrate to some other method of db initialization

kubectl exec cockroachdb-0  -- /cockroach/cockroach init --certs-dir='/cockroach/cockroach-certs'; /cockroach/cockroach sql --certs-dir='/cockroach/cockroach-certs' < /docker-entrypoint-initdb.d/schema.sql
