version: '3.8'

services:
  resume:
    container_name: resume
    build: src
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - './src:/app'
    networks:
      - 'backend'

  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v22.2.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: res_it
    ports:
      - '3306:3306'
    volumes:
      - './db:/var/lib/mysql'
      - './db_init:/docker-entrypoint-initdb.d/'
    networks:
      - 'backend'

networks:
  backend:

volumes:
  src:
  db:
