#!/bin/bash

docker container rm -f "$(docker container ls | grep resume | awk '{print $1}' | cut -d: -f2)"
docker rmi -f "$(docker image ls | grep resume | awk '{print $3}')"
docker build --no-cache -t resume .
docker run -p "80:80" resume
