apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
  labels:
    app: resume-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      containers:
      - name: resume-backend
        image: resume-backend
        imagePullPolicy: IfNotPresent #change to Always when online
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
#  type: LoadBalancer #Not on Minikube?
  selector:
    app: resume-backend
  ports:
  - protocol: TCP
    #nodePort: 30080 #exposes outside cluster
    port: 5000 #exposes within cluster
    targetPort: 5000 #sends requests to this port
---
apiVersion: v1
kind: Deployment
metadata:
  name: resume-frontend
  labels:
    app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      containers:
      - name: resume-frontend
        image: resume-frontend
        imagePullPolicy: IfNotPresent #change to Always when online
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort #switch to LoadBalancer online so nodePort can be 8080
  selector:
    app: resume-frontend
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 80
    targetPort: 80
